### PR TITLE
Walgreens (Hyannis) fix

### LINKED ISSUE #97: Walgreens (Hyannis) showing incorrect availability
The site is currently showing "1 slot" available at Walgreens (Hyannis).  However, we I run the scraper locally my result shows _no availability._

### PR DESCRIPTION
**Pull request by harcod**
Fixes #97  (two ways)

1. Ignores any cached item without a timestamp. (@Iann has a separate PR #91 that properly sets the timestamp for future Walgreens locations)
2. Changed the cache key to remove all vowels and 0.

This will remove all of the vowels and the '0' from the key.
**road, rd** match as _rd_
**02601, 2601** match as _261_

Then the merge code won't use the old bad data.

Here are sample keys for Walgreens (Hyannis) and Walgreens (Pittsfield)

> wlgrnshynns|52wmnst|hynns|261
> wlgrnspttsld|37chshrrd|pttsld|121

### CODE REVIEW

File: data/dataDefaulter.js [hunk 1]
```diff
@@ -42,7 +40,7 @@ function generateKey(entry) {
         if (entry[key]) {
             uniqueIdentifier += `${entry[key]
                 .toLowerCase()
-                .replace(/[^\w]/g, "")}|`;
+                .replace(/[^1-9bcdghj-np-tv-z]/g, "")}|`; // remove spaces, vowels, and 0
```
Comment (livgust) [inline data/dataDefaulter.js:43]: I like where your head is at but I feel like this might be too lax and could cause bugs down the road...

I feel more strongly about not ignoring vowels than I do not ignoring 0s, but let me know how you feel.

The road/rd is a good call out but I'd personally prefer doing that on purpose, like road/rd, avenue/ave, street/st, circle/cir etc.

**Review by livgust — CHANGES_REQUESTED** [review]

File: data/dataDefaulter.js (hunk 1 above)
Comment (iann) [reply data/dataDefaulter.js:43]: Maybe we just match on less criteria for Walgreens specifically? Say `walgreenshyannis|{streetNum}|{zipWithoutZeros}` eg. `walgreenshyannis|52|261`. With this approach we do run the risk of having for instance a Walgreens with the same street number in the same zip code causing a collision.

Comment (iann) [reply data/dataDefaulter.js:43]: Or maybe this list helps. https://www.walgreens.com/storelistings/storesbycity.jsp?state=MA

Comment (harcod) [reply data/dataDefaulter.js:43]: I was just trying to repair the persistent bug on the site.  I suppose we could also fix this on the front-end (if the data is never going away) by not showing appointments that are in the past.

Or, you can run this code ONE time and fix the file, then immediately revert to the old method.

Comment (livgust) [reply data/dataDefaulter.js:43]: The first fix should cause the second Hyannis to be removed, since it doesn't have an associated timestamp yet. I'll merge this but revert this specific change, unless someone feels strongly about it or I'm missing something... (I'd normally wait for us to get consensus but I want to get this out tonight)

**Review by livgust — APPROVED** [review]
